server {
    listen 8080;
    server_name webserv_test;
    root ./www;
    client_max_body_size 1048576;

    error_page 404 /404.html;

    location / {
        allowed_methods GET POST;
        autoindex on;
        index index.html;
    }
}



Metodos que no existes
acceso archivos y directorios (permisos)
puertos distintos
tamaño negativo mal en client max body
codigos de error existentes
redirecciones con codigos de error (evitar devolver codigos erroneos)
evitar doble listen
comprobar nuevos servidores con los anteriores (puerto, name y root)
Root de location debe partir del root del server

tirar error si algo falla, si faltan datos rellenar con lso valores
default para tener un servidor funcional pero reducido