server {
    listen 8080;
    server_name webserv_test;
    root ./www;
    client_max_body_size 1048576;

    error_page 404 /404.html;

    location / {
        allowed_methods GET POST;
        autoindex on;
        index index.html;
    }
}