server {
    listen 127.0.0.1:8081;
    server_name alpha.localhost;
    root ./www;
    client_max_body_size 0;

    location / {
        allowed_methods GET;
        root ./www;
        index index.html;
        autoindex off;
    }
}

server {
    listen 127.0.0.1:8081;
    server_name beta.localhost;
    root ./YoupiBanane;
    client_max_body_size 0;

    location / {
        allowed_methods GET;
        root ./YoupiBanane;
        index youpi.bad_extension;
        autoindex on;
    }
}

server {
    listen 127.0.0.1:8081;
    server_name localhost;
    root ./www;
    client_max_body_size 0;

    location / {
        allowed_methods GET;
        root ./www;
        index index.html;
        autoindex off;
    }
}
