# ==============================================================================
# WEBSERV CONFIGURATION FILE (MVP)
# ==============================================================================

# First Server: Main Testing Server
server {
    listen 8080;
    server_name miedon1;
    root ./www;
    client_max_body_size 1048576;

    # Global server error pages (Parsed at server level)
    error_page 404 /error_pages/404.html;

    location / {
        root ./www/;
        autoindex on;
        index index.html;
        allowed_methods GET POST DELETE;
    }

    location /images/ {
        root ./www;
        autoindex on;
        index default.jpg fallback.png;
        allowed_methods GET POST;
    }

    location /uploads/ {
        upload_path ./www/uploads;
        autoindex off;
        allowed_methods GET POST DELETE;
    }

    location /legacy/ {
        return 301 https://www.youtube.com;
        allowed_methods GET;
    }

    location /users/ {
        autoindex on;
        allowed_methods GET;
    }
}

# Second Server: Secondary Port Testing
server {
    listen 8081;
    server_name miedon1;
    root ./www_server2;
    client_max_body_size 1048576;

    location / {
        root ./www;
        autoindex on;
        index index.html;
        allowed_methods GET;
    }

    location /cgi-bin/ {
        root ./www_server2/cgi-bin/;
        upload_path ./www_server2/uploads;
        index default.cgi;
        allowed_methods GET POST;
    }
}